version: "3.6"

services:
  web:
    build: .
    image: registry.heroku.com/${HEROKU_APP:-k3s-server}/web
    volumes:
      - ./app:/app
      - ./kubernetes:/kubernetes
    privileged: true
    environment:
      - PORT=6443
      - DATABASE_URL=postgres://k3s:k3s@postgres:5432/k3s
      - K3S_KUBECONFIG_OUTPUT=/kubernetes/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    ports:
      - 6443:6443

  redis:
    image: redis:alpine

  postgres:
    image: postgres:9.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=k3s
      - POSTGRES_PASSWORD=k3s
      - POSTGRES_DB=k3s
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
