#!/bin/sh
set -eu

_err() {
  >&2 echo "err: $*"
  exit 1
}

if [ "${REDIS_URL:-}" != "" ]; then
  password_and_rest=${REDIS_URL##*h:}
  host_and_port=${password_and_rest#*@}

  password=${password_and_rest%@*}
  redis_host=${host_and_port%:*}
  redis_port=${REDIS_URL##*:}

  redis_auth="*2\r\n\$4\r\nAUTH\r\n\$${#password}\r\n$password\r\n"
else
  redis_auth=""
  redis_host="redis"
  redis_port="6379"
fi

case "${1:-}" in
  set)
    kubeconfig=$(cat $2)
    printf "$redis_auth*3\r\n\$3\r\nset\r\n\$10\r\nKUBECONFIG\r\n\$${#kubeconfig}\r\n$kubeconfig\r\n" | busybox nc $redis_host $redis_port
  ;;
  get)
    printf "$redis_auth*2\r\n\$3\r\nget\r\n\$10\r\nKUBECONFIG\r\n" | busybox nc $redis_host $redis_port | tail -n+3
  ;;
  *)
    _err "usage: get|set"
  ;;
esac
